const projects = [
  {
    course: "Medication Tracking Mobile App (BetterHealth App)",
    university: "Loyola Marymount University",
    desc: [
      "Applied several HCI principles learned throughout the semester in a group project to ideate, design and build an app prototype to remind forgetful medicine takers to record their mood and dose intake.",
      "Submitted four reports and a 10 minute video that summarized group findings about user research and effectiveness of prototype to improve app design periodically.",
      "Evaluated classmates’ prototype designs to learn the importance of aesthetics and designing with the end user in mind to create interfaces.",
    ],
    tech: [
      "User Interface Design",
      "Teamwork",
      "HCI Design Principles",
      "Prototyping",
      "Documentation",
      "Peer Reviews",
    ],
  },
  {
    course: "React Country Data Finder Web App",
    university: "Loyola Marymount University",
    desc: [
      "Created a React App that uses a combination of HTML, CSS, and React that fetches information such as Common Name, Official Name, Population, Region, Subregion, Flag, Capital, Continent, and Time Zones of countries a user searches for.",
      "Incorporated complex components such as a form with user inputs, which allows for streamlined API calls.",
      "Developed a cohesive and responsive user interface through the use of involved CSS concepts such as grid and flex, while using symmetry in the image placement to create a balanced visual appearance.",
      "Validated code by using a HTML accessibility validator.",
    ],
    tech: [
      "Rest Countries API",
      "React",
      "JavaScript",
      "HTML",
      "CSS",
      "Color Schemes",
      "Google Fonts",
    ],
    preview: [
      ["On GitHub Pages", "https://speer987.github.io/react-country-finder/"],
      ["On CodeSandbox", "https://q839ng.csb.app/"],
    ],
    code: [
      ["GitHub", "https://github.com/speer987/react-country-finder"],
      [
        "CodeSandbox",
        "https://codesandbox.io/p/sandbox/react-country-data-finder-q839ng?file=%2Fsrc%2Findex.js",
      ],
    ],
  },
  {
    course: "Compound Interest Calculator Web App",
    university: "Loyola Marymount University",
    desc: [
      "Developed an app by incorporating various HTML and CSS concepts that allow users to calculate their compound interest",
      "[ENTER MORE HERE]",
      "[ENTER MORE HERE]",
    ],
    tech: ["HTML", "CSS", "JavaScript", "Google Fonts", "Color Schemes"],
    preview: [
      [
        "On GitHub Pages",
        "https://speer987.github.io/compound-interest-calculator/",
      ],
      ["On CodeSandbox", "https://loxvgn.csb.app/"],
    ],
    code: [
      ["GitHub", "https://github.com/speer987/compound-interest-calculator"],
      [
        "CodeSandbox",
        "https://codesandbox.io/p/sandbox/compound-interest-calculator-loxvgn?file=%2Findex.html%3A4%2C29",
      ],
    ],
  },
  {
    course: "React Nutrition Web App",
    university: "Loyola Marymount University",
    desc: [
      "Worked alongside two others to build a Nutrition App that allows health concious individuals to search for recipes that are within a certain range of calories, carbs etc.",
      "Wrote documentation that detailed various aspects of the app, which included [ENTER STUFF HERE]",
      "[ENTER MORE HERE]",
    ],
    tech: [
      "React",
      "Spoonacular API",
      "CSS",
      "HTML",
      "Firebase/Firestore",
      "Google Authentication",
      "Google Fonts",
    ],
    code: [["Github", "https://github.com/joanna-estrada/nutrition"]],
  },
  {
    course: "React Book Wishlist/Tracking Web App (The Book Nook)",
    university: "Loyola Marymount University",
    // desc: ["I like pie."],
    tech: [
      "React.js",
      "HTML",
      "CSS",
      "Javascript",
      "Open Library API",
      "Google Books API",
      "New York Times Best Selling Book API",
      "Google Authentication via Firebase",
      "Firestore",
      "Firebase Hosting",
      "Chart.js",
      "Tailwind CSS",
      "Gantt Charts",
      "Weekly Presentations",
      "Peer Reviews",
      "Poster Boarding",
      "Google Fonts",
    ],
    code: [["Github", "https://github.com/speer987/the-book-nook"]],
    preview: [["On Firebase Hosting", "https://the-book-nook-5c098.web.app/"]],
  },
  {
    course: "Website for Client with Special Needs",
    university: "Pace University",
    desc: [
      "Designed and developed a fully functional website using the Wix CMS to assist a person with disabilities in showcasing their skills and building their professional network.",
      "Bolstered communication skills and developed a good eye for design through constant discussion with a client to build a professional website layout that suited their needs.",
    ],
  },
  {
    course: "Command Line Utility (mkfid - Make File in Directory)",
    university: "Loyola Marymount University",
    desc: ["I like pie."],
    tech: ["C", "Unix", "Presentation Skills", "Teamwork"],
  },
  {
    course: "Rose Hack",
    university: "UC Riverside",
    // desc: [],
    tech: ["CSS", "HTML", "Teamwork"],
  },
  {
    course: "LMU Marketplace Mobile App",
    university: "Loyola Marymount University",
    desc: ["This is currently in progress for Spring 2024."],
    tech: [
      "Software Engineering Principles",
      "Documentation",
      "React Native Paper",
      "React Native",
      "Firestore",
      "Firebase Authentication",
      "XCode Simulator",
      "Google Fonts",
    ],
  },
];

export default projects;
