const projects = [
  {
    course: "Medication Tracking Mobile App (BetterHealth App)",
    university: "Loyola Marymount University",
    desc: [
      "Applied several HCI principles learned throughout the semester in a group project to ideate, design and build an app prototype to remind forgetful medicine takers to record their mood and dose intake.",
      "Submitted four reports and a 10 minute video that summarized group findings about user research and effectiveness of prototype to improve app design periodically.",
      "Evaluated classmates’ prototype designs to learn the importance of aesthetics and designing with the end user in mind to create interfaces.",
    ],
    tech: [
      "User Interface Design",
      "Teamwork",
      "HCI Design Principles",
      "Prototyping",
      "Documentation",
      "Peer Reviews",
    ],
  },
  {
    course: "React Country Data Finder Web App",
    university: "Loyola Marymount University",
    desc: [
      "Created a React App that uses a combination of HTML, CSS, and React that fetches information such as Common Name, Official Name, Population, Region, Subregion, Flag, Capital, Continent, and Time Zones of countries a user searches for from the Country API.",
      "Incorporated complex components such as a form with a user input, which queries the Country API for country details, which are displayed underneath the form.",
      "Developed a cohesive and responsive user interface through the use of involved CSS concepts such as grid and flex, while using symmetry in the image placement to create a balanced, simple visual appearance.",
      "Validated code by using a HTML accessibility validator.",
    ],
    tech: [
      "Rest Countries API",
      "React",
      "JavaScript",
      "HTML",
      "CSS",
      "Color Schemes",
      "Google Fonts",
    ],
    preview: [
      ["On GitHub Pages", "https://speer987.github.io/react-country-finder/"],
      ["On CodeSandbox", "https://q839ng.csb.app/"],
    ],
    code: [
      ["GitHub", "https://github.com/speer987/react-country-finder"],
      [
        "CodeSandbox",
        "https://codesandbox.io/p/sandbox/react-country-data-finder-q839ng?file=%2Fsrc%2Findex.js",
      ],
    ],
  },
  {
    course: "Compound Interest Calculator Web App",
    university: "Loyola Marymount University",
    desc: [
      "Developed an app by incorporating various HTML and CSS concepts that allow users to calculate their compound interest on a uniform and aesthetically pleasing interface.",
      "Used numerous CSS concepts such as transform, border width and color, and grid, which allowed for the symmetrical and responsive placement of images and content.",
      "Incorporates the use of four different user input fields (one being a number), which are validated upon form submission for easily calculating compound interest.",
      "Ensured that users are presented with an error message when entering erroneous inputs.",
      "Utilized a basic javascript function knowledge to calculate compound interest before displaying it to the user interface.",
    ],
    tech: ["HTML", "CSS", "JavaScript", "Google Fonts", "Color Schemes"],
    preview: [
      [
        "On GitHub Pages",
        "https://speer987.github.io/compound-interest-calculator/",
      ],
      ["On CodeSandbox", "https://loxvgn.csb.app/"],
    ],
    code: [
      ["GitHub", "https://github.com/speer987/compound-interest-calculator"],
      [
        "CodeSandbox",
        "https://codesandbox.io/p/sandbox/compound-interest-calculator-loxvgn?file=%2Findex.html%3A4%2C29",
      ],
    ],
  },
  {
    course: "React Nutrition Web App",
    university: "Loyola Marymount University",
    desc: [
      "Worked alongside two other team members to build a Nutrition App that allows health concious individuals to search for recipes or to get three randomly generated recipes, which also shows a user's most recent favorited recipe from Firestore.",
      "Developed a grid form layout with a gradient background to allow users to search for recipes that have a particular max ready time, or amount of max carbs, max protein and max calories.",
      "Ensured the smooth development of the search and random recipe generator page to display recipes in a 2x2 grid of a 3x1 grid.",
      "Queried the Spoonacular API to show information on recipe cards such as recipe image, summary, link, favorite recipe button, serving amount, ready time, and a nutrition label.",
      "Utilized two API endpoints from the Spoonacular API on both the search and random recipe generator.",
    ],
    tech: [
      "React",
      "Spoonacular API",
      "CSS",
      "HTML",
      "Firebase/Firestore",
      "Google Authentication",
      "Google Fonts",
    ],
    code: [["Github", "https://github.com/joanna-estrada/nutrition"]],
  },
  {
    course: "React Book Wishlist/Tracking Web App (The Book Nook)",
    university: "Loyola Marymount University",
    // desc: ["I like pie."],
    tech: [
      "React.js",
      "HTML",
      "CSS",
      "Javascript",
      "Open Library API",
      "Google Books API",
      "New York Times Best Selling Book API",
      "Google Authentication via Firebase",
      "Firestore",
      "Firebase Hosting",
      "Chart.js",
      "Tailwind CSS",
      "Gantt Charts",
      "Weekly Presentations",
      "Peer Reviews",
      "Poster Boarding",
      "Google Fonts",
    ],
    code: [["Github", "https://github.com/speer987/the-book-nook"]],
    preview: [["On Firebase Hosting", "https://the-book-nook-5c098.web.app/"]],
  },
  {
    course: "Website for Client with Special Needs",
    university: "Pace University",
    desc: [
      "Designed and developed a fully functional website using the Wix CMS to assist a person with disabilities in showcasing their skills and building their professional network.",
      "Bolstered communication skills and developed a good eye for design through constant discussion with a client to build a professional website layout that suited their needs.",
    ],
  },
  {
    course: "Command Line Utility (mkfid - Make File in Directory)",
    university: "Loyola Marymount University",
    desc: ["I like pie."],
    tech: ["C", "Unix", "Presentation Skills", "Teamwork"],
  },
  {
    course: "Rose Hack",
    university: "UC Riverside",
    // desc: [],
    tech: ["CSS", "HTML", "Teamwork"],
  },
  {
    course: "LMU Marketplace Mobile App",
    university: "Loyola Marymount University",
    desc: ["This is currently in progress for Spring 2024."],
    tech: [
      "Software Engineering Principles",
      "Documentation",
      "React Native Paper",
      "React Native",
      "Firestore",
      "Firebase Authentication",
      "XCode Simulator",
      "Google Fonts",
    ],
  },
];

export default projects;
