const skills = [
  "Python",
  "React",
  "Java",
  "C",
  "JavaScript",
  "Cypher (Neo4J)",
  "SQL",
  "Firebase",
  "Firestore",
  "Communication Skills",
  "Presentation Skills",
  "Teamwork",
  "R",
  "React Native",
  "Prototyping",
  "Tailwind CSS",
  "React Native Paper",
  "CSS",
];
export default skills;
